project:
  type: website
  output-dir: _site

website:
  title: "陈浩的个人主页"
  site-url: https://haochen-co.github.io/my-personal-site
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: about.qmd
        text: 关于我
  sidebar:
    style: docked

format:
  html:
    theme: cosmo
    css: styles.css



